########## FROZEN STAGE ##########
FROM ros:melodic-ros-core AS ros1_bridge_stage

RUN apt update \
  && apt install -y --no-install-recommends \
  curl \
  gnupg2 \
  lsb-release \
  locales \
  && curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add - \
  && echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list \
  && locale-gen en_US en_US.UTF-8 \
  && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

ENV LANG=en_US.UTF-8

RUN apt update \
  && apt install -y --no-install-recommends ros-eloquent-ros-base \
  ros-eloquent-ros1-bridge  \
  ros-eloquent-demo-nodes-cpp

COPY ros1bridge_entrypoint.sh /ros1bridge_entrypoint.sh
ENTRYPOINT [ "/ros1bridge_entrypoint.sh" ]
CMD ros2 run ros1_bridge dynamic_bridge --bridge-all-topics
