FROM ros:eloquent-ros-base

RUN apt update \
  && apt install -y --no-install-recommends \
  ros-${ROS_DISTRO}-demo-nodes-cpp

COPY ros2_entrypoint.sh /ros2_entrypoint.sh

ENTRYPOINT ["/ros2_entrypoint.sh"]
CMD ros2 run demo_nodes_cpp add_two_ints_client
